services:
  app:
    build:
      context: .
      target: app-dev
      args:
        purpose: dev
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    user: root
    entrypoint:
      - sh
      - -c
    networks:
      - proxy
    environment:
      # let the websocket work
      - PORT=80
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=snooker.docker,not-a-host.ydns.eu
      - LETSENCRYPT_HOST=not-a-host.ydns.eu
      - HTTPS_METHOD=redirect
    command:
      - |
        set -x
        npm i
        node --openssl-legacy-provider node_modules/react-scripts/scripts/start.js | cat

volumes:
  node-modules: {}

networks:
  proxy:
    external: true
