services:
  app:
    image: docker-hub.squiz.net/docker/base-images/node:18-alpine
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    working_dir: /app
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_PROTO=http
    networks:
      - docker_proxy
    #ports:
    #  - "127.0.0.1:80:3000"
    #  - "8880:3000"

volumes:
  node-modules: {}

networks:
  docker_proxy:
    external: true
